/*
 * Copyright (C) 2012 Clarion Media, LLC
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clarionmedia.infinitum.internal.caching;

import java.io.File;
import android.content.Context;

/**
 * <p>
 * Contains static utility methods for DEX caching.
 * </p>
 * 
 * @author Tyler Treat
 * @version 1.0 07/12/12
 * @since 1.0
 */
public class DexCaching {

	/**
	 * Name of the DEX cache directory
	 */
	private static final String DEX_CACHE = "dex_cache";

	/**
	 * Retrieves the application DEX cache directory for generated bytecode.
	 * 
	 * @param context
	 *            {@link Context}
	 * @return DEX cache
	 */
	public static File getDexCache(Context context) {
		return context.getDir(DEX_CACHE, Context.MODE_PRIVATE);
	}

}
