/*
 * Copyright (c) 2012 Tyler Treat
 * 
 * This file is part of Infinitum Framework.
 *
 * Infinitum Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Infinitum Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Infinitum Framework.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.clarionmedia.infinitum.internal.caching;

import java.io.File;
import android.content.Context;

/**
 * <p>
 * Contains static utility methods for DEX caching.
 * </p>
 * 
 * @author Tyler Treat
 * @version 1.0 07/12/12
 * @since 1.0
 */
public class DexCaching {

	/**
	 * Name of the DEX cache directory
	 */
	private static final String DEX_CACHE = "dex_cache";

	/**
	 * Retrieves the application DEX cache directory for generated bytecode.
	 * 
	 * @param context
	 *            {@link Context}
	 * @return DEX cache
	 */
	public static File getDexCache(Context context) {
		return context.getDir(DEX_CACHE, Context.MODE_PRIVATE);
	}

}
